# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161223_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='us_city_state',
        ),
        migrations.AddField(
            model_name='location',
            name='us_city',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='us_state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
