# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20161224_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
