#API_KEY = "2tab9fyvrvuiYrReaH0hE"
#SECRET_KEY = "PIUgxrZ53NwHNdV71yyQF7PfA6r2laPyNLj99pfL"
#WEATHER_BASE_URL = "http://api.aerisapi.com"
API_KEY = "950398e05e71a9c0"
WEATHER_BASE_URL = "http://api.wunderground.com/api"
DJANGO_APP = "weather_app_site"
AUTHOR_ADDRESS = "tmiskell@morphotrust.com"
TITLE = "Weather Powered Email"
